version: 2
updates:
  - package-ecosystem: pip
    directory: "/backend"
    schedule:
      interval: weekly
      day: monday
    labels:
      - skip-changelog
      - dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: weekly
      day: monday
    labels:
      - skip-changelog
      - dependencies
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    labels:
      - skip-changelog
      - dependencies
