services:
  backend:
    image: backend:dev
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
      - valkey
    ports:
      - "8000:8000"
    env_file:
      - backend/.env
    environment:
      - POSTGRES_HOST=db
  db:
    image: postgres:17-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "scan"
    volumes:
      - db-data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:8-alpine
    expose:
      - 6379
    ports:
      - 6379:6379
    command: valkey-server --requirepass test_password

volumes:
  db-data:

networks:
  scan-network:
