services:
  backend:
    image: backend:dev
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=someKey
      - FIRST_SUPERUSER_EMAIL=some@email.com
      - FIRST_SUPERUSER_PASSWORD=somePassword!
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_DB=scan
      - OPENAI_API_KEY=someKey
  db:
    image: postgres:17-alpine
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test_password"
      POSTGRES_DB: "scan"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

networks:
  scan-network:
